{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "15c47ddf-874b-4653-ac7f-0bdee5c10e01",
   "metadata": {},
   "outputs": [],
   "source": [
    "url_soleil='https://static.data.gouv.fr/resources/donnees-du-temps-densoleillement-par-departements-en-france/20221207-142648/temp\n",
    "\n",
    "consumption_data_url_2018=\"https://enedis.opendatasoft.com/api/explore/v2.1/catalog/datasets/consommation-annuelle-residentielle-par-adresse/exports/csv?lang=fr&refine=annee%3A%222018%22&timezone=Europe%2FBerlin&use_labels=true&delimiter=%3B\"\n",
    "consumption_data_url_2019= \"https://enedis.opendatasoft.com/api/explore/v2.1/catalog/datasets/consommation-annuelle-residentielle-par-adresse/exports/csv?lang=fr&refine=annee%3A%222019%22&timezone=Europe%2FBerlin&use_labels=true&delimiter=%3B\"\n",
    "consumption_data_url_2020=\"https://enedis.opendatasoft.com/api/explore/v2.1/catalog/datasets/consommation-annuelle-residentielle-par-adresse/exports/csv?lang=fr&refine=annee%3A%222020%22&timezone=Europe%2FBerlin&use_labels=true&delimiter=%3B\"\n",
    "consumption_data_url_2021=\"https://enedis.opendatasoft.com/api/explore/v2.1/catalog/datasets/consommation-annuelle-residentielle-par-adresse/exports/csv?lang=fr&refine=annee%3A%222021%22&timezone=Europe%2FBerlin&use_labels=true&delimiter=%3B\"\n",
    "\n",
    "import bs4\n",
    "import lxml\n",
    "import pandas\n",
    "import urllib\n",
    "from urllib import request\n",
    "\n",
    "class Meteo :\n",
    "    def __init__(self):\n",
    "        self.data_all = {\n",
    "                i : {j : {} for j in range(1,13)} for i in range(2011,2019)\n",
    "            }\n",
    "\n",
    "    def scrap(self):\n",
    "        for y in self.data_all :\n",
    "            for m in self.data_all[y] :\n",
    "                url_test = 'https://www.infoclimat.fr/stations-meteo/analyses-mensuelles.php?mois=' + str(m) + '&annee=' + str(y)\n",
    "                raw_text = request.urlopen(url_test).read()\n",
    "                page = bs4.BeautifulSoup(raw_text,'lxml')\n",
    "                tableau = page.find('table', {'id' : 'tableau-releves'})\n",
    "                rows = tableau.find_all('tr')\n",
    "        \n",
    "                df = {\n",
    "            'Villes' : [rows[i].find('a').text for i in range(1,len(rows))], #[rows[i].find_all('div')[0].text for i in range(1,len(rows))], #[rows[i].find('a').text for i in range(1,len(rows))],\n",
    "            'Température minimale extrême du mois' : [rows[i].find('div').text for i in range(1,len(rows))],\n",
    "            'Moyenne des températures minimales du mois' : [rows[i].find_all('td')[2].text for i in range(1,len(rows))],\n",
    "            'Température moyenne du mois' : [rows[i].find_all('td')[3].text for i in range(1,len(rows))],\n",
    "            'Moyenne des températures maximales du mois' : [rows[i].find_all('td')[4].text for i in range(1,len(rows))],\n",
    "            'Température maximale extrême du mois' : [rows[i].find_all('td')[5].find('div').text for i in range(1,len(rows))],\n",
    "            'Cumul de précipitation du mois' : [rows[i].find_all('td')[6].text for i in range(1,len(rows))],\n",
    "            \"Heure d'ensolleiment du mois\" : [rows[i].find_all('td')[7].text for i in range(1,len(rows))],\n",
    "            'Rafale maximale du mois' : [rows[i].find_all('td')[8].text for i in range(1,len(rows))] \n",
    "                    }\n",
    "        \n",
    "                self.data_all[y][m] = df\n",
    "\n",
    "    def export(self):\n",
    "        self.df_all = pandas.DataFrame(self.data_all)\n",
    "        self.df_all.to_json('data_base.json')\n",
    "\n",
    "    def rename(self):\n",
    "        self.df_all = pandas.DataFrame(self.data_all)\n",
    "        self.df_all.rename({'Villes' : 'ville', \n",
    "           'Température minimale extrême du mois' : 'tnn',\n",
    "           'Moyenne des températures minimales du mois' : 'tnm', \n",
    "           'Température moyenne du mois' : 'tmm', \n",
    "           'Moyenne des températures maximales du mois' : 'txm', \n",
    "           'Température maximale extrême du mois' : 'txx', \n",
    "           'Cumul de précipitation du mois' : 'rr', \n",
    "           \"Heure d'ensolleiment du mois\" : 'ens', \n",
    "           'Rafale maximale du mois' : 'rafale'}, axis=1, inplace = True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
